on: push
jobs:
  github_actions_test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: BuildnPush Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push 
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ghcr.io/aminayusufova/github_actions_test:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
